api:
  base_url: "https://offer.cdn.begmedia.com/api/pub/v6/events/"
  countrycode: "fr"
  language: "fr"
  sitecode: "frfr"

logging:
  level: "INFO"
  file: "betclic_scraper.log"

email:
  sender: "adressedeparis@gmail.com"
  recipients:
    - "julesdebisschop@gmail.com"
    - "hippolyte2510@gmail.com"
  password: "syri qfyu uppr tkjl"  # Consider using environment variables for sensitive information

data:
  output_directory: "data"
  new_file: "ace_market_data_new.json"
  old_file: "ace_market_data_old.json"
  changes_file: "changes.json"

scheduler:
  interval: 600  # 10 minutes in seconds

database:
  host: "localhost"
  port: 5432
  dbname: "betclic_data"
  user: "postgres"  # Replace with your actual PostgreSQL username
  password: "Jesuisneen1998@PG"  # Replace with your actual PostgreSQL password
